# Generated by Django 4.2.7 on 2024-01-27 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blok',
        ),
    ]
