# Generated by Django 4.2.7 on 2023-12-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mieszkaniec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('indeks', models.CharField(blank=True, max_length=7)),
                ('nazwa', models.CharField(blank=True, max_length=255)),
                ('adres', models.CharField(blank=True, max_length=255)),
                ('klatka', models.CharField(blank=True, max_length=2)),
                ('telefon', models.CharField(blank=True, max_length=9)),
                ('symbol_budynku', models.CharField(blank=True, max_length=4)),
                ('zgoda', models.CharField(choices=[('tak', 'tak'), ('nie', 'nie')], default='tak', max_length=3)),
                ('administracja', models.CharField(choices=[('NS', 'NS'), ('NW', 'NW'), ('CE', 'CE')], default='CE', max_length=2)),
                ('content', models.TextField(blank=True, max_length=160)),
                ('phone', models.TextField(blank=True, max_length=9)),
            ],
        ),
    ]
