# Generated by Django 4.2.7 on 2024-01-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_utworzenia', models.CharField(blank=True, max_length=15)),
                ('indeks_blok', models.CharField(blank=True, max_length=7)),
                ('adres_blok', models.CharField(blank=True, max_length=255)),
                ('osiedle_blok', models.CharField(blank=True, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Mieszkaniec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_utworzenia', models.CharField(blank=True, max_length=15)),
                ('indeks', models.CharField(blank=True, max_length=7)),
                ('nazwa', models.CharField(blank=True, max_length=255)),
                ('adres', models.CharField(blank=True, max_length=255)),
                ('klatka', models.CharField(blank=True, max_length=2)),
                ('telefon', models.CharField(blank=True, max_length=9)),
                ('symbol_budynku', models.CharField(blank=True, max_length=4)),
                ('zgoda', models.CharField(choices=[('tak', 'tak'), ('nie', 'nie')], default='tak', max_length=3)),
                ('administracja', models.CharField(choices=[('NS', 'NS'), ('NW', 'NW'), ('CE', 'CE')], default='CE', max_length=2)),
                ('content', models.TextField(blank=True, max_length=160, null=True)),
                ('phone', models.TextField(blank=True, max_length=9, null=True)),
            ],
        ),
    ]
