# Generated by Django 4.2.7 on 2023-12-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefony', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mieszkaniec',
            name='data_utworzenia',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
