# Generated by Django 4.2.7 on 2024-01-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefony', '0003_alter_mieszkaniec_content_alter_mieszkaniec_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10000)),
            ],
        ),
    ]
