# Generated by Django 4.2.7 on 2024-01-27 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telefony', '0005_blok'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blok',
        ),
    ]
