# Generated by Django 4.2.7 on 2024-01-27 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telefony', '0006_delete_blok'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
    ]
