# Generated by Django 4.2.7 on 2024-01-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefony', '0007_delete_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_utworzenia', models.CharField(blank=True, max_length=15)),
                ('indeks_blok', models.CharField(blank=True, max_length=7)),
                ('adres_blok', models.CharField(blank=True, max_length=255)),
                ('osiedle_blok', models.CharField(blank=True, max_length=3)),
            ],
        ),
    ]
