# Generated by Django 4.2.7 on 2024-03-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefony', '0008_blok'),
    ]

    operations = [
        migrations.AddField(
            model_name='mieszkaniec',
            name='telefon_2',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='mieszkaniec',
            name='telefon_3',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
