# Generated by Django 4.2.7 on 2024-03-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefony', '0009_mieszkaniec_telefon_2_mieszkaniec_telefon_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mieszkaniec',
            name='zgoda',
            field=models.CharField(choices=[('tak', 'Tak'), ('nie', 'Nie')], default='tak', max_length=3),
        ),
    ]
