# Generated by Django 4.2.7 on 2024-03-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefony', '0010_alter_mieszkaniec_zgoda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mieszkaniec',
            name='telefon_2',
        ),
        migrations.RemoveField(
            model_name='mieszkaniec',
            name='telefon_3',
        ),
        migrations.AlterField(
            model_name='mieszkaniec',
            name='zgoda',
            field=models.CharField(choices=[('tak', 'tak'), ('nie', 'nie')], default='tak', max_length=3),
        ),
    ]
