# Generated by Django 4.2.7 on 2024-03-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefony', '0011_remove_mieszkaniec_telefon_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mieszkaniec',
            name='telefon2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='mieszkaniec',
            name='telefon3',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
