# Generated by Django 4.2.7 on 2024-03-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefony', '0012_mieszkaniec_telefon2_mieszkaniec_telefon3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mieszkaniec',
            name='telefon',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
