# Generated by Django 4.2.7 on 2024-04-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefony', '0013_alter_mieszkaniec_telefon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mieszkaniec',
            name='phone',
            field=models.TextField(blank=True, null=True),
        ),
    ]
