# Generated by Django 4.2.7 on 2024-02-15 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('umowy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='contract_files/')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umowy.contract')),
            ],
        ),
    ]
