# Generated by Django 4.2.7 on 2024-02-15 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('umowy', '0002_contractfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractfile',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='umowy.contract'),
        ),
    ]
