# Generated by Django 4.2.7 on 2024-02-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umowy', '0003_alter_contractfile_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='notification_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
