# Generated by Django 4.2.7 on 2024-02-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umowy', '0005_remove_contract_notification_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(default='Active', max_length=100),
        ),
    ]
