# Generated by Django 4.2.7 on 2024-02-15 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umowy', '0007_alter_contract_status_alter_contractfile_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='file',
        ),
    ]
