# Generated by Django 4.2.7 on 2024-02-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umowy', '0008_remove_contract_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='contract_files/')),
            ],
        ),
        migrations.DeleteModel(
            name='ContractFile',
        ),
        migrations.AddField(
            model_name='contract',
            name='files',
            field=models.ManyToManyField(to='umowy.file'),
        ),
    ]
