# Generated by Django 4.2.7 on 2024-02-17 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('umowy', '0009_file_delete_contractfile_contract_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='contract_files/')),
            ],
        ),
        migrations.RemoveField(
            model_name='contract',
            name='files',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.AddField(
            model_name='contractfile',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umowy.contract'),
        ),
    ]
