# Generated by Django 4.2.7 on 2024-02-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umowy', '0010_contractfile_remove_contract_files_delete_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
