# Generated by Django 4.2.7 on 2024-02-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umowy', '0011_alter_contract_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
