# Generated by Django 4.2.7 on 2024-03-12 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umowy', '0015_contractfileannex'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContractFileAnnex',
        ),
    ]
