# Generated by Django 4.2.7 on 2024-03-12 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umowy', '0017_contractfile_is_annex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractfile',
            name='is_annex',
        ),
    ]
