# Generated by Django 4.2.7 on 2024-03-13 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('umowy', '0018_remove_contractfile_is_annex'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractFileAnnex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_annex', models.FileField(upload_to='contract_files/')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umowy.contract')),
            ],
        ),
    ]
