# Generated by Django 4.2.7 on 2024-03-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umowy', '0019_contractfileannex'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='place',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
