# Generated by Django 4.2.7 on 2024-03-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umowy', '0020_contract_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='indefinite',
            field=models.DateField(blank=True, null=True),
        ),
    ]
