# Generated by Django 4.2.7 on 2024-03-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umowy', '0021_contract_indefinite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='indefinite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
