# Generated by Django 4.2.7 on 2024-03-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umowy', '0022_alter_contract_indefinite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
            ],
        ),
    ]
