# Generated by Django 4.2.7 on 2024-03-05 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('estate', models.CharField(choices=[('NW', 'Nowe Wzgórze'), ('NS', 'Nowe Sady'), ('CE', 'Centrum')], max_length=2)),
                ('street', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress')], max_length=20)),
                ('added_date', models.DateField(auto_now_add=True)),
                ('planned_execution_date', models.DateField()),
                ('actual_execution_date', models.DateField(blank=True, null=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domofony.contractor')),
            ],
        ),
    ]
