# Generated by Django 4.2.7 on 2024-03-05 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domofony', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskIntercom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('estate', models.CharField(choices=[('NW', 'Na Wyżynach'), ('NS', 'Na Skarpie'), ('CE', 'Centrum')], max_length=2)),
                ('street', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress')], max_length=20)),
                ('added_date', models.DateField(auto_now_add=True)),
                ('planned_execution_date', models.DateField()),
                ('actual_execution_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Contractor',
            new_name='ContractorIntercom',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AddField(
            model_name='taskintercom',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domofony.contractorintercom'),
        ),
    ]
