# Generated by Django 4.2.7 on 2024-03-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('surname', models.CharField(blank=True, max_length=100, null=True)),
                ('administration', models.CharField(blank=True, max_length=3, null=True)),
                ('address_ip_pc', models.CharField(blank=True, max_length=20, null=True)),
                ('login', models.CharField(blank=True, max_length=20, null=True)),
                ('domain_name', models.CharField(blank=True, max_length=30, null=True)),
                ('pc_name', models.CharField(blank=True, max_length=20, null=True)),
                ('office_pass', models.CharField(blank=True, max_length=10, null=True)),
                ('address_ip_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address_ip_phone_second', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_pass', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
