# Generated by Django 4.2.7 on 2024-03-20 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='UsersIT',
        ),
    ]
