# Generated by Django 4.2.7 on 2024-02-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('powod', models.CharField(max_length=500)),
                ('dotyczy', models.CharField(max_length=1000)),
                ('data_pozew', models.CharField(blank=True, max_length=20, null=True)),
                ('wyrok1', models.TextField(blank=True, max_length=1000)),
                ('wyrok2', models.TextField(blank=True, max_length=1000)),
                ('egzekucja', models.TextField(blank=True, max_length=1000)),
                ('uwagi', models.TextField(blank=True, max_length=2000)),
                ('zakonczenie', models.TextField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('Zakonczono', 'Zakonczono'), ('W trakcie realizacji', 'W trakcie realizacji'), ('Zawieszone', 'Zawieszone')], default='Zakonczono', max_length=22)),
                ('kto', models.CharField(choices=[('Pozew przeciwko Spółdzielni', 'Pozew przeciwko Spółdzielni'), ('Pozew przez Spółdzielnię', 'Pozew przez Spółdzielnię')], max_length=50)),
                ('phone', models.CharField(choices=[('500524230', 'Asystentka'), ('601521658, 601202139', 'Zarzad'), ('694704533', 'Radca'), ('601521657', 'IT'), ('601521658, 601202139, 500524230, 694704533', 'Wszyscy')], default='601521658, 601202139', max_length=100)),
                ('content', models.TextField(blank=True, max_length=160)),
                ('opis', models.CharField(blank=True, max_length=255)),
                ('plik', models.FileField(upload_to='')),
            ],
        ),
    ]
