# Generated by Django 4.2.7 on 2024-02-25 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='plik',
        ),
        migrations.AddField(
            model_name='record',
            name='file',
            field=models.FileField(blank=True, default=True, upload_to='records/files/'),
        ),
        migrations.CreateModel(
            name='ContractFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='records/files/')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rss.record')),
            ],
        ),
    ]
