# Generated by Django 4.2.7 on 2024-03-22 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0002_remove_record_plik_record_file_contractfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Record',
            new_name='RecordRss',
        ),
    ]
