# Generated by Django 4.2.7 on 2024-03-22 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0003_rename_record_recordrss'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecordRss',
            new_name='Record',
        ),
    ]
