# Generated by Django 4.2.7 on 2024-03-22 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0005_remove_record_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='contract_files/')),
                ('record_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rss.record')),
            ],
        ),
        migrations.DeleteModel(
            name='ContractFile',
        ),
    ]
