# Generated by Django 4.2.7 on 2024-03-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0006_recordfile_delete_contractfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='record_files/'),
        ),
    ]
