# Generated by Django 4.2.7 on 2024-03-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0007_record_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='file',
        ),
        migrations.AlterField(
            model_name='recordfile',
            name='file',
            field=models.FileField(upload_to='record_files/'),
        ),
    ]
