# Generated by Django 4.2.7 on 2024-02-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pracownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Zadanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('comments', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('added_date', models.DateTimeField(default=True)),
                ('deadline', models.DateField()),
                ('task_photo', models.ImageField(blank=True, upload_to='task_photos/')),
                ('signature_image', models.ImageField(blank=True, upload_to='signature_images/')),
                ('assigned_to', models.ManyToManyField(related_name='tasks', to='pracownik.pracownik')),
            ],
        ),
    ]
