# Generated by Django 4.2.7 on 2024-02-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracownik', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zadanie',
            name='added_date',
            field=models.DateTimeField(),
        ),
    ]
