# Generated by Django 4.2.7 on 2024-02-11 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pracownik', '0004_task_taskassignment_taskcomment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='additional_task_photos/')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_photos', to='pracownik.task')),
            ],
        ),
    ]
